### ISSUE TITLE
[BUG] [app]The homepage UI is wrong, there is an icon missing in the upper right corner.

### ISSUE THREAD

**Issue by longyuqing112** [openimsdk/openmeeting#1]
### OpenIM Server Version

e.g 3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

The homepage UI is wrong, there is an icon missing in the upper right corner.
![微信截图_20240709181242](https://github.com/openimsdk/openmeeting/assets/105913803/96655652-288d-4ba8-8722-f694f0d5ad97)

**Comment by std-s** [comment]
目前没有通讯录功能，先不管它。
