### ISSUE TITLE
[BUG] 【app】Occasionally: The homeowner kicks the member out of the meeting, and the member's mobile phone pop-up window reports an abnormal error

### ISSUE THREAD

**Issue by longyuqing112** [openimsdk/openmeeting#16]
### OpenIM Server Version

e.g 1.0.0+4

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

Occasionally: The homeowner kicks the member out of the meeting, and the member's mobile phone pop-up window reports an abnormal error

**Comment by std-s** [comment]
member: t3  host: t2 password: 1 time: Around 11:50
